@startuml
title Smart House Module Management Code Diagram

top to bottom direction

!includeurl ./C4_Component.puml

class Module {
  +String title
  +List<Membership> memberships
  +void add()
}

class Device {
  +String type
  +void register()
  +void unregister()
}

Module "1" -- "0..*" Device : has

@enduml
